# This is a basic workflow to help you get started with Actions

name: Test 1Password OIDC Integration

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      id-token: write # Required for GitHub to issue the OIDC token

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Inspect OIDC Token Claims
        run: |
          ACTIONS_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://1password.com" | jq -r '.value')
          
          # Extract and decode the JWT payload
          echo "$ACTIONS_TOKEN" | cut -d'.' -f2 | base64 --decode | jq .

      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v5
        with:
          export-env: true
        env:
          OP_WORKLOAD_ID: "YG2JPAFZQNAQFCN4NF4RMO4ZQY"
          OP_ENVIRONMENT_ID: "mtxmra332m5hvv2iog67y5ccaq"
          OP_INTEGRATION_KEY: ${{ secrets.OP_INTEGRATION_KEY }}

      - name: Verify Environment Variable
        run: |
          if [ -n "$MY_VAR" ]; then
            echo "MY_VAR was loaded successfully from 1Password Environment."
          else
            echo "MY_VAR is empty or missing."
            exit 1
          fi
